name: Markdown Links Check

# Check links on main branch push
on:
  push:
    branches:
      - "link-checker"
  schedule:
    - cron: '0 0 * * * ' # At the end of everyday
  workflow_dispatch: # Or manually from GitHub UI

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          folder-path: "docs/*/**.md"
      - uses: actions/checkout@v3
